# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 19:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('user_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
