# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rink_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthdata',
            name='monthYear',
            field=models.CharField(max_length=50),
        ),
    ]
